# Generated by Django 5.2.7 on 2025-12-06 05:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab_editor', '0002_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_id', models.CharField(db_index=True, default='default', max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('file', 'File'), ('folder', 'Folder')], default='file', max_length=10)),
                ('content', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='collab_editor.virtualfile')),
            ],
            options={
                'verbose_name': 'Virtual File',
                'verbose_name_plural': 'Virtual Files',
                'ordering': ['type', 'name'],
                'unique_together': {('room_id', 'parent', 'name')},
            },
        ),
    ]
