# Generated by Django 5.2.7 on 2025-12-06 14:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab_editor', '0004_room_roommember'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('author_name', models.CharField(default='Unknown', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('size', models.IntegerField(default=0)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='collab_editor.virtualfile')),
            ],
            options={
                'verbose_name': 'File Snapshot',
                'verbose_name_plural': 'File Snapshots',
                'ordering': ['-created_at'],
            },
        ),
    ]
